
random_state: 42
target_column: Attrition
target_value: "Yes"
train_frac: 0.8

preprocessing:
  categorical_cols: ["Gender", "JobRole", "OverTime"]
  number_cols: ["Age", "TotalWorkingYears", "MonthlyIncome", "JobLevel", "TrainingTimesLastYear","YearsAtCompany","YearsInCurrentRole","YearsSinceLastPromotion","YearsWithCurrManager"]
  expected_cols: ['Age', 'TotalWorkingYears', 'MonthlyIncome', 'JobLevel',
       'TrainingTimesLastYear', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Gender_Female',
       'Gender_Male', 'JobRole_Healthcare Representative',
       'JobRole_Human Resources', 'JobRole_Laboratory Technician',
       'JobRole_Manager', 'JobRole_Manufacturing Director',
       'JobRole_Research Director', 'JobRole_Research Scientist',
       'JobRole_Sales Executive', 'JobRole_Sales Representative',
       'OverTime_No', 'OverTime_Yes']
train:
  n_iter: 500 
  cv: 3
  verbose: 2
  random_state: 42 
  n_jobs: -1
  random_grid:
    n_estimators: [15, 25, 30, 50,100]
    max_features: [sqrt]
    max_depth: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]
    min_samples_split: [2, 6, 10, 15]
    min_samples_leaf: [1, 3, 4, 5, 6, 7, 9, 10] 
    bootstrap: [True, False] 
